### ISSUE TITLE
Cannot build since #199 fix

### ISSUE THREAD

**Issue by AloisMahdal** [fanglingsu/vimb#211]
I just pulled from master and tried to `make`, and I get syntax error related to inclusion of hints.js (snipping the tremendous line sample, full version posted [to pastebin][1]):

    cc hints.o
    In file included from hints.c:28:0:
    hints.c: In function ‘hints_init’:
    hints.js.h:1:5160: error: expected ‘)’ before ‘HINT_CSS’
     #define HINTS_JS "Object.freeze((function(){ [SNIP]
     [SNIP]
    hints.c:64:49: note: in expansion of macro ‘HINTS_JS’
             hints.obj = js_create_object(hints.ctx, HINTS_JS);
                                                     ^
    hints.c: At top level:
    cc1: warning: unrecognized command line option "-Wno-typedef-redefinition"
    Makefile:38: recipe for target 'hints.o' failed
    make[1]: *** [hints.o] Error 1
    Makefile:43: recipe for target 'vimb' failed
    make: *** [vimb] Error 2

  [1]: http://pastebin.com/KWGUPs3A

git bisect reveals the first commit affected by this is 476b624 - "Moved default hint css from js to config.def.h file (#199)".

My box is Debian Jessie on x86_64.

**Comment by cmkarlsson** [comment]
You need to delete src/config.h and make again. This is same as #206  so please have a look there for more information
